spring.application.name=varastonseuranta

# H2
spring.datasource.url=jdbc:h2:mem:testdb

# h2 consolen asetukset
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#API
spring.data.rest.base-path=/api